version: '3.8'

services:
  app:
    build:
      context: .   # Points to your Next.js project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
